.env, package.json, src/App.vue, src/components/ContextCard.vue, src/components/DatasetCard.vue, src/components/SideBar.vue, src/components/SidebarContent.vue, src/components/Tabs.vue, src/components/scaffold-meta-map.js
Each tab has it's own search and is switched to with `v-show`
=> Added tabs and context cards to sidebar

package.json, src/App.vue, src/components/DatasetCard.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
This can be viewed at https://jesses-sparc-science.herokuapp.com/maps
=> Add neuron search

package.json, src/components/DatasetCard.vue
This is a fix for scaffold which do not have annotations that gives them an 'organ' listing in 'anatomy' under a scicrunch result
=> Add check for organ labels

package.json, src/App.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
Create callback when the search term or filters have been modified.
=> Emit event

package-lock.json, package.json, src/components/SearchFilters.vue, src/components/SidebarContent.vue
Sidebar should now support an array of filters passed into using the open search function.
Use AbortController to abort previous search if a new search has been performed before previous call has completed.
Refactor some part of the codes.
=> Filters and other fixes

package.json, src/algolia/algolia.js, src/components/SidebarContent.vue
This was quite a specific request and seeing as scicrunch is up to date (all of our datasets are showing) I thought I would fulfill it
=> Switch to using dois for finding datasets as opposed to discover ids

package-lock.json, package.json, src/App.vue, src/components/ContextCard.vue, src/components/DatasetCard.vue, src/components/SearchFilters.vue, src/components/SidebarContent.vue
Added context cards and a help pop up for how the filters work
- context card now returns action view viewURLs for scaffold
- help pop up uses css from the design system
- added new filter 'Data type'
=> Context cards via scicrunch

package.json, src/components/ContextCard.vue, src/components/DatasetCard.vue, src/components/SidebarContent.vue, src/components/hardcoded-context-info.js
- Added v-loading for context card
- Fix for 'files/files/' on thumbnails
- Added hardcoded data for datasets 221 and 77
- Added samples with toggle for detailed descriptions
- Fix image sizing
=> Add hardcoded data and ability to display samples:

package.json, src/components/ContextCard.vue, src/components/DatasetCard.vue, src/components/SidebarContent.vue
[Context card fixes:](https://github.com/ABI-Software/map-sidebar/pull/30/commits/ec9e6f1ce360a4f095493b9a6e4d4155d497a013) 
[ec9e6f1](https://github.com/ABI-Software/map-sidebar/pull/30/commits/ec9e6f1ce360a4f095493b9a6e4d4155d497a013)
- Fix context card witdth expanding the sidebar width
- Fix context card not clearing when next item is clicked
- Add a max-width to the context card
- Change font size to match dataset card items
- Update version number
=> Contex cards via scicrunch

src/components/DatasetCard.vue, src/components/ImageGallery.vue
Banners urls are passed from the dasetcard to context card to save a request
They got removed and will not show without this fix
=> Fix for context card banners

package-lock.json, package.json, src/App.vue, src/algolia/algolia.js, src/algolia/utils.js, src/components/ContextCard.vue, src/components/SearchFilters.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
Keywords for the current search can now be retrieved from algolia. These are a list of uberons that can be used to update the flatmap markers
=> Add keyword search

package.json, src/algolia/algolia.js, src/algolia/utils.js, src/components/ContextCard.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
Found a few typos and things to clean up
=> Keyword search typo fixes

package-lock.json, package.json, src/components/ContextCard.vue
An example of how this works can be found here:
https://jsfiddle.net/tehsurfer/gkvw5rL7/23/
=> Switch to using markdown and checking for XSS

package-lock.json, src/components/BadgesGroup.vue, src/components/ImageGallery.vue
Add a new dataset badge and rename Biolucida Images badge to Images.
Wrike ticket here - https://www.wrike.com/open.htm?id=970446374
=> Change Biolucida Images badge to Images and add a Dataset badge.

.gitignore, package-lock.json, package.json, src/App.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
Remove unused variable.
OpenSearch with current search term when the component is mounted.
=> Refactoring

package.json, src/algolia/utils.js, src/components/SearchFilters.vue
Algolia facet prop paths have been changed on algolia to meet these tickets:
https://www.wrike.com/open.htm?id=1068218399
https://www.wrike.com/open.htm?id=1068218007
=> Sidebar feedback sprint 27

package-lock.json, package.json, src/components/ContextCard.vue, src/components/ImageGallery.vue, src/mixins/S3Bucket.vue
Add s3 uri for relevant resources.
=> Support S3 bucket for all related resources

package.json, src/App.vue, src/algolia/algolia.js, src/components/DatasetCard.vue, src/components/SideBar.vue, src/components/SidebarContent.vue
- Disable the context card
- Add an emit for facet labels
=> Mapintegrated context cards

package-lock.json, src/components/SearchFilters.vue, src/components/SearchHistory.vue, src/components/SidebarContent.vue
Add search history
Note that you need 6 unique search history items to get the select box to appear
=> Add in basic but functional search history

package.json, src/algolia/algolia.js, src/components/SideBar.vue, src/components/SidebarContent.vue
Adds an emit for the anatomy markers
=> Anatomy markers

package-lock.json, package.json, src/App.vue, src/components.d.ts, src/components/ConnectivityInfo.vue, src/components/SideBar.vue, src/components/Tabs.vue
1. Show tooltips on flatmap for connectivity mouse over/out 4ce257d9411416f5bec2745a59bb0e87bb11b5c3
=> Making connectivity entries interactive

src/components/SideBar.vue
Uses information from provided tabs props. This will allow having different tabs ordering and search tab will no longer be compulsory if we decide to.
=> computed props - activeTabs 

src/components/ConnectivityInfo.vue, src/components/SideBar.vue
- Make connectivity error on graph and list more consistent - pass connectivityError as props.
- Update the way how error message label is generated.
=> Magnify glass search

src/components/ConnectivityInfo.vue
- add population id
- always show sckan vs map (if map source not exist, show sckan instead)
https://github.com/user-attachments/assets/b0d79b4c-89e2-4a59-a9be-48396fecbb74
=> Explorer update

src/components/ConnectivityCard.vue, src/components/ConnectivityExplorer.vue
https://github.com/ABI-Software/mapintegratedvuer/pull/299
=> Feature: connectivity knowledge multiview

src/components/ConnectivityInfo.vue
Match the colour for disabled copy button.
=> Match colour for disabled copy button.

src/App.vue, src/components/ConnectivityCard.vue, src/components/ConnectivityExplorer.vue, src/components/ConnectivityInfo.vue, src/components/SideBar.vue
Add card loading for different cases
=> Update explorer card display

src/components/ConnectivityExplorer.vue, src/components/SearchFilters.vue, src/components/SideBar.vue
- Make sure the filter will be updated once the filter entry changes
- Changes the search-changed emit content
- Fix the search history function
- Fix long label tag display
=> Explorer filter

src/components/ConnectivityExplorer.vue, src/components/SearchFilters.vue
=> Update filter option style

src/components/ConnectivityExplorer.vue
Card will not be expanded by default.
=> Update sidebar card display behaviour

src/components/ConnectivityCard.vue, src/components/ConnectivityExplorer.vue, src/components/SearchFilters.vue
Should fix the tag style in the portal.
=> Update nerve tag style

src/algolia/algolia.js, src/components/SearchFilters.vue
Provide the label curie mapping and store it in the local storage.
=> Store label curie mapping in local storage.
